### ISSUE TITLE
Copy/Paste Maya locator screen space position, to 3D Equalizer 2D point

### ISSUE THREAD

**Issue by MichaelKarp** [david-cattermole/mayaMatchMoveSolver#141]
In mmSolver we can already Copy the camera from Maya and then paste all parameters to the camera in 3D Equalizer.

It would be great to have a similar feature for Copy/Paste of Maya 3d locators, to 3D Equalizer 2d track points.

In Maya animated locators, groups, rivets and/or rig controllers, etc. would be selected. Then an mmSolver Copy command would (internally) 2d bake the screen space position of the e.g. locator, to the Clipboard.

Then in 3D Equalizer there would be a Paste_2d command, which would either paste the 2d position to the selected 3DE points, or create new points. Whichever is easiest to implement.

**Comment by david-cattermole** [comment]
Hello Michael,

Yes, this is possible to implement.
I am tempted to make the tool only support Markers to be exported to .uv files, rather than allow any Maya 3D transform directly, because I believe it would make more sense for users. If arbitrary 3D transforms need to be exported then the "Convert to Marker" tool should be used.

Exporting only Markers would also allow us to automatically export 3DE metadata that's stored on the Marker node directly.

Example use case:
1) In 3DE, Create and track a 2D point.
2) Use the Copy Tracks (MM Solver) tool.
3) In Maya, use the Load Markers tool to load the .uv file in Maya.
4) Modify the 2D Marker in Maya using whatever tool the user wants to use.
5) Apply lens undistortion (when issue #106 is available.)
6) Select Marker(s) in Maya and use a "Copy Markers" tool (to be written.
7) In 3DE, run a "Paste 2D Tracks (MM Solver)". Similar logic to Maya's Load Marker tool should be used to re-apply 2D data to 2D points in 3DE. The paste tool in 3DE must ask if undistorted or distorted 2D data is wanted, the default will be "distorted".
8) Repeat steps 1-7 until desired.

Michael does that cover your use case? 

Also note I do not consider this a high priority feature, as I'm not sure this workflow is a common use case.

David

**Comment by MichaelKarp** [comment]
Yes, it makes perfect sense to limit the tool to mmSolver Markers. Much
less programming work for you and very little extra work for the user.

Yes, this issue is lower priority, since Patcha and I have the Kuper
workaround. But we have found that a sophisticated rotomation pipeline
involves exporting Maya 3D points to 3DE 2D.

Here is part of the background. In the old days (2003) I would export 4
corner pins from a Maya card, to e.g. Combustion. Shake did not have a
native 3D camera then, so 3D points in Maya would commonly be converted to
2D for the compositing software. But since 3D cameras are now ubiquitous in
Comp, the need for tools to bake 3D points to 2d is greatly reduced. But it
is not gone. We still have the 3DE 2.5D MEL export and all of the Reel In
and Bake Distortion to 2D commands. So the basic idea is very much part of
modern thinking, but I occasionally need the 2.5D export to go the opposite
direction between 3DE and Maya.

**Comment by david-cattermole** [comment]
Hello @MichaelKarp,

As a proof of concept I have written a simple script to export mmSolver Markers as .uv files:
[writemarker_maya.py.txt](https://github.com/david-cattermole/mayaMatchMoveSolver/files/6872347/writemarker_maya.py.txt)

To test this:
1) Rename the file to remove .txt
2) Save in your Maya "scripts" directory
3) Select some mmSolver Marker nodes.
4) Run this Python code:
```python
import writemarker_maya
writemarker_maya.main()
```

With the .uv file created you will be able to load it back into Maya (using the "Load Markers" tool).

The next step would be to write a .uv file importer for 3DEqualizer.

David

**Comment by david-cattermole** [comment]
Hello @MichaelKarp,

I have written a crude mmSolver Marker .uv file importer for 3DEqualizer4 R3+.
3DEqualizer4 R7 (Python 3.x) is not test or supported.

Similar to the previous Maya exporter, you will need to rename the file and remove the ".txt" file extension. Otherwise, simply install this into your `${HOME}/.3dequalizer/py_scripts` directory and then in the Object Browser, right-click on a point group and choose "Import 2D Tracks (MM Solver)... v1.0".

[import_tracks_mmsolver.py.txt](https://github.com/david-cattermole/mayaMatchMoveSolver/files/6874494/import_tracks_mmsolver.py.txt)

This importer is crude and does not support the following features:
- Original 3DE marker name is not saved (round trip while updating same 2D point is not possible)
- 3D survey position is not set from Bundle location.
- Start frame on camera is assumed to be set correctly to align with Maya frame numbers.
- 3DE point animated weight value is not set.
- 3DE point colour is not set.
- Camera Overscan compensation is not automatically calculated in any way.
- Lens distortion is ignored - all 2D data is imported "as is", no apply/removal of lens distortion is performed.

Please give this a test along with the .uv file exporter and let me know how it goes.

I have also found a bug in the above "writemarker_maya.py" file, which is now fixed, please update:
[writemarker_maya.py.txt](https://github.com/david-cattermole/mayaMatchMoveSolver/files/6874493/writemarker_maya.py.txt)
The fixed bug caused Markers written to ignore the "enable" Marker attribute in Maya.

David

**Comment by david-cattermole** [comment]
Michael has confirmed the above scripts are working as expected, for basic functionality.

**Comment by david-cattermole** [comment]
After some tweaks and better integration this feature is ready for release in v0.4.0.

Closing unless something comes up.

**Comment by david-cattermole** [comment]
The code that will be released is mostly the same as the above example scripts except I have allowed the "3D survey position" to be set from the Bundle location stored in the .uv file.

The following limitations still exist and may be addressed in the future:

- Original 3DE marker name is not saved (round trip while updating same 2D point is not possible)
- Start frame on camera is assumed to be set correctly to align with Maya frame numbers.
- 3DE point animated weight value is not set.
- 3DE point colour is not set.
- Camera Overscan compensation is not automatically calculated in any way.
- Lens distortion is ignored - all 2D data is imported "as is", no apply/removal of lens distortion is performed.

Additionally, these tools are Python 3 compatible and work in Maya 2022+, and are expected to work in 3DEqualizer R7+.
