### ISSUE TITLE
Install/Build errors for Maya 2016 Extension 2 (2016.5)

### ISSUE THREAD

**Issue by ktonegawa** [david-cattermole/mayaMatchMoveSolver#148]
### Problem / Feature
I tried to "install" this plugin via the released 2016 win64 zip file but my Maya won't read anything in the */modules* directory, and when attempting to manually browse to the .mll file i get the following error:

```
// Error: file: C:/Program Files/Autodesk/Maya2016.5/scripts/others/pluginWin.mel line 767: Unable to dynamically load : C:/Users/Desktop02/Documents/maya/2016.5/modules/mayaMatchMoveSolver-0.2.0-maya2016-win64/plug-ins/mmSolver.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2016.5/scripts/others/pluginWin.mel line 767: The specified module could not be found.
 (mmSolver) // 
```
I then attempted to try to build this plugin via the source, but I keep running into issues. I am using Visual Studio 2017, so I used the *x64_x86 Cross Tools Command Prompt for VS 2017* in place of what was specified in the documentation, and every build attempt after following the instructions I am faced with errors looking like this (this is a paste from Visual Studio 2017 after generating project files from enabling `GENERATE_SOLUTION`):

https://pastebin.com/HzxLed93

I suspected this may have been because of incompatibility issues with 2017 (when the documentation calls for VS 2012 Update 5), so I installed that exact version and attempt another build but I keep running into a similar issue.

I have tried all the ideas I can come up with my limited knowledge, including trying to update the toolsets/target(?) in the VS solution to Windows 8 SDK/v141, but none seemed to work.

I understand that I do have an older version of Maya, but would it be possible to get some assistance on this issue...?

### Software Versions
CMake 3.17.3
Python 2.7.12

- mmSolver version:
source

- Maya version:
Operating System: Microsoft Windows 7 Business Edition, 64-bit Windows 7 Service Pack 1 (Build 7601)

Cut ID: 201603022110-988944-2
Maya Version: Autodesk Maya 2016 Extension 2
Maya API: 201650
Qt Version: 4.8.6
Compositing Manager: True
Window Manager: Windows Aero
GPU:   Version : 2015.11.4.11. Feature Level 5.
  Adapter : GeForce GTX 560 Ti/PCIe/SSE2
  Vendor ID: 4318. Device ID : 4608
  Driver : nvoglv64.dll:23.21.13.9135.
  API : OpenGL V.4.6.
  Max texture size : 16384 * 16384.
  Max tex coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 1024 MB.
  CPU Memory Limit: 31107 MB.

- Operating System (OS):
Windows

**Comment by david-cattermole** [comment]
Hello @ktonegawa,

Thanks for reporting this with a lot detail!
That is very appreciated!

The versions of compilers are set specifically by the Maya Developer API documentation, and are quite important to use.
I would recommend using Visual Studio 2012 Update 4 for Maya 2016.5, and setting up the build environment like this:
https://help.autodesk.com/view/MAYAUL/2016/ENU/?guid=__files_Setting_up_your_build_env_Windows_env_32bit_and_64bit_htm

Looking at the pastebin log, 2 few things standout to me:

- `C:\MinGW\include\stdio.h` is from MinGW (with GCC on windows), and is not compatible with Maya. It appears your includes are finding stdio.h from GCC, not from Visual Studio. Perhaps try to remove MinGW from your include path inside Visual Studio? Or change the environment variable order to ensure Visual Studio includes are found first. Or as a last resort, uninstall MinGW.

- `12>'rcc' is not recognized as an internal or external command,` is the QT resource icon generation process, which is a minor failure (you won't have icons in the Solver UI). this is because Qt is not installed, which is an annoying dependency which is not yet stripped from the build process. I am looking to remove this dependency and instead use the Maya devkit (which includes the executable already).

I'll see if I can reproduce this problem. 
I often compile with `GENERATE_SOLUTION=0` from the Windows Command Line directly, so I admit this isn't very well tested on my end.

**Comment by david-cattermole** [comment]
As a side note to this issue, I have created a separate issue about the missing `rcc` package. #149

**Comment by ktonegawa** [comment]
Hello @david-cattermole , thank you so much for your response.

With what you were saying, these are the steps I took:

1. re-installed VS 2012 with Update 4
2. re-generated a solution/project for this plugin
3. removed `C:\MinGW` from the "Additional Includes Directories" in Visual Studio
4. replaced `COMMAND rcc -binary resources.qrc -o resources.rcc` in `icons\CMakeLists.txt` to `COMMAND C:/Python27/Lib/site-packages/PyQt4/pyrcc4.exe -o resources.rcc resources.qrc` (I had to do something similar for the `sphinx-build` anyways)

After doing all of that I re-compiled the solution, and it seemed to work? although there were a lot of warnings, hoping that these are expected.../

https://pastebin.com/bpf1U4vD

And I saw that a .mod file and a directory identically named to your latest release were generated, but just copying those didn't really do anything, so what I ended up doing was taking the release zip file and extracting that, but replaced the .mll plugin file with what was generated on my end. I also noticed that if I left the .mod file the way it was my version of Maya still did not load anything, so as a guess I changed the `+ PLATFORM:win64 MAYAVERSION:2016 mayaMatchMoveSolver 0.3.6 ` line in the mod file to `+ PLATFORM:win64 MAYAVERSION:2016.5 mayaMatchMoveSolver 0.3.6 ` and that made everything load up fine.

Thank you so much for your assistance, I am looking forward to exploring your tool's capabilities

As an additional note, I attempted a build using VS2017 with following most of the steps I laid out above, but that unfortunately failed, here is the log if you are interested...

https://pastebin.com/a85bddUg

**Comment by david-cattermole** [comment]
Thank you @ktonegawa for letting others know how you've solved the problem!

You have helped to stop [this](https://xkcd.com/979/) from happening ;)

### Warnings
Regarding the excessive warnings produced, I have made a little reminder to myself as part of #152 to stop this from happening.
The warnings are only warnings, and will not stop the plug-in from compiling or running.

### Maya Modules
I'm sorry you had to do so much to get the module working, but it sounds like it's working correctly for you.

I think you should have been able to change `SET MAYA_VERSION=2016` to `SET MAYA_VERSION=2016.5` and it would have worked:
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/scripts/build_mmSolver_windows64_maya2016.bat#L31

### Qt RCC Executable
That's unfortunate you need to manually edit the CMake file, but it's a quick workaround.
Maya also contains the executable in: `C:\Program Files\Autodesk\Maya2016\bin\rcc.exe`, and it should be the exact version required (no incompatibilities).

I have created an issue to remove this problem in future: #150

### Getting Started
The documentation has some information (including video tutorials) to get you started and provide some written help;
https://david-cattermole.github.io/mayaMatchMoveSolver/

If you have questions, please join the (currently private) Google Group, or if you find a bug (or you have a question and you don't want to join the Google Group) submit an issue to the GitHub page and I'll try to answer as soon as I can.
https://groups.google.com/forum/#!forum/maya-matchmove-solver

Thank you,
David

P.S. I had chosen not to support Maya 2016.5 because of the binary incompatibility between "Maya 2016" and "Maya 2016 Extension 2" and (anecdotally) the lack of industry use caused by that.

**Comment by david-cattermole** [comment]
As a side note about compiling with VS2017, the VFX Reference Platform is looking to include Microsoft Windows support in 2021, and in the recent Academy Software Foundation talk, they mentioned that from VS2017 the ABI is guaranteed to be stable.

https://www.youtube.com/watch?v=xNCeo9mjVNs

However, my recommendation would always be to follow the Maya API Documentation regarding compiler versions to avoid any ABI incompatibility.

**Comment by ktonegawa** [comment]
Hi @david-cattermole, about the private Google Group, whenever I keep clicking on that link it keeps giving me a "Content Unavailable" page with no real option to request to join or anything. Is there anything I would need to do to join in on these conversations...?

And I totally understand the lack of support for 20126 Extension 2, I knew it was very old to begin with but this is the version I use at home to do any sorts of tests...

**Comment by david-cattermole** [comment]
@ktonegawa, please try the Google Group again, I didn't realise.
I have changed the permissions - but you should be able to "Ask to Join".

**Comment by ktonegawa** [comment]
Thank you @david-cattermole , I have sent in a request to join...

**Comment by ktonegawa** [comment]
I know this issue is closed, but for anyone who finds this topic still having build issues on Windows:

I have Avast Antivirus installed on my system and it has become apparent to me recently that you MUST DISABLE Avast to be able to actually run VS2012 x64 Cross Tools Command Prompt (or anything related) and run any of the `.bat` script files. Its annoying, but this works. I guess this is a Visual Studio/Microsoft bug. 

This actually is also the case for doing any installation/re-installing of Visual Studio products (although for this you actually need to **uninstall** Avast or perhaps other anti-virus software). Check this thread here for more info: https://developercommunity.visualstudio.com/content/problem/1086700/visual-studio-2019-install-stuck-on-installer-gett.html

It's really interesting to see this ticket was closed as `Not a bug`. How is having anti-virus software blocking an installation of this software NOT a bug? Are they claiming its some kind of feature? I don't know.
