### ISSUE TITLE
Maya Tool - Create Controller tool v2

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#193]
Tool should support to create controller in different spaces.
Tool should support full bake, smart bake and current frame bake as well.

**Comment by david-cattermole** [comment]
This tool has just been merged in #192.

The last steps will be to write documentation (which I will do), and @bpatchasaheb will make a video tutorial for upload.

**Comment by david-cattermole** [comment]
I have added some documentation here;
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/develop_v0.3.x/docs/source/tools_generaltools.rst#create--remove-controller

The only part we're missing is a video tutorial. I will put that video tutorial on the mmSolver YouTube channel and put a link in the documentation.

I am closing this issue because it's finished and ready for release.
