### ISSUE TITLE
Solver UI - Need minimal Solver UI while solving

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#195]
It would be nice to have a minimal Solver UI while solving to get more room in the viewport.
Preferably mmSolver can hide few widgets which we might not need while solving, for instance input & output widgets.
Progress bar with "Stop Solve" and "Close" buttons would be helpful to see the solve progress.

**Comment by kapilsonig** [comment]
It will be a time saver and good for single monitor task 👍🏻

**Comment by david-cattermole** [comment]
Thanks Patcha, I can see how this would be helpful.

I think also having a preference to turn it on/off will be important.
I have not decided if this should be on or off by default. I'll probably make the decision after I've implemented the feature.

> Progress bar with "Stop Solve" and "Close" buttons would be helpful to see the solve progress.

Changing the solve button text is reported in #185 too (just mentioning it to create the link in GitHub).

**Comment by ktonegawa** [comment]
It would also be good to make the UI actually dockable or treated as a panel within Maya. I remember David mentioning that we could potentially just inherit all Windows from `maya.app.general.mayaMixin.MayaQWidgetDockableMixin` instead of the current `maya.app.general.mayaMixin.MayaQWidgetBaseMixin`. But I am not entirely sure if this also means it can be treated as a "Panel". It would even be a better idea to some how port the Solver UI to be treated like a "Graph Editor".

**Comment by david-cattermole** [comment]
Good point @ktonegawa I have documented that in #197.

**Comment by david-cattermole** [comment]
This feature has been added:

![image](https://user-images.githubusercontent.com/891288/105630667-60cf8f80-5e42-11eb-9404-c57feb692f5d.png)

The feature will be controlled by a new User Preference option (configurable with the `mmSolver > General Tools > User Preferences...` menu item), and will be *enabled* by default.

This feature has been merged and will be released in v0.3.12.

**Comment by david-cattermole** [comment]
Hold up - this works on Maya 2016, 2017, and 2018, but fails to work on Maya 2019... re-opening.

**Comment by david-cattermole** [comment]
This is now working in Maya 2019, and will be released in v0.3.12.
