### ISSUE TITLE
Can't get solver to run

### ISSUE THREAD

**Issue by mswed** [david-cattermole/mayaMatchMoveSolver#205]
Hi, I'm trying to get a solve running on and object track and for some reason, I keep getting the following warning:

Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve

And it looks like the solver just stops without actually solving. 

Here's what I've done:
1. Created fresh scene (under the assumption my original file got corrupted somehow)
2. Imported a camera from 3de.
3. Imported an obj file (which lines up with my plate)
4. Imported 2D tracks from 3de using the Export 3D Tracks (MM Solver) v1.7 (I also tried Copy 2D tracks (MM Solver) v1.8, with the same results)
5. Selected the markers in the mmSolver UI and then hit tools > Project Marker on Mesh (Ray-Cast)
6. Most of the markers hit the geo
7. selected the obj file, and keyed all channels. 
8. Clicked the + sign near Output Attributes in the mmSolver UI which added all of the channels to the UI. 
9. Hit solve. 

### Software Versions

- mmSolver version:
mmSolver Version: v0.3.11
mmSolver Module: mayaMatchMoveSolver-0.3.11-maya2019-win64
Maya Version: Autodesk Maya 2019
Maya API: 20190000
Maya Cut ID: 201812112215-434d8d9c04
Qt Version: 5.6.1

- Maya version:
2019 (looks like no service packs are installed)

- Operating System (OS):
Windows 10

Any idea what I might be doing wrong?

Thanks, 

Moshe

**Comment by david-cattermole** [comment]
Hello Moshe,

Thank you for your detailed description - it makes things a lot faster and easier to debug for me :)

The reason the solve is not working is that you need to have more 2D points for the number of attributes to solve.

For example to solve 6 attributes per-frame (translate XYZ and rotate XYZ) you need a *minimum* of 3 points (2 x 6 - X and Y for each 2D Marker) on each frame.

In v0.3.11 the "validate" button has been hidden by default, however this button can help spot these problems.
To turn it on:
1) Open the menu `mmSolver > General Tools > User Preferences...` (right at the bottom)
2) Set `Show Validate Button` to `Yes`.
3) Press "Save" button
4) Re-open the Solver UI.
5) Press `Validate` button.

User Preferences:
![image](https://user-images.githubusercontent.com/891288/105095986-5ad25b00-5a9e-11eb-9031-941108f30322.png)

Solver UI Validate button:
![image](https://user-images.githubusercontent.com/891288/105096436-f95ebc00-5a9e-11eb-911d-7902be9646bb.png)

The numbers in the text will give you some helpful information.
- Valid Solves - Number of individual solve steps (usually number of frames) that have enough information.
- Invalid Solves - Opposite of Valid Solves.
- Deviations - Number of 2D coordinates (X and Y)
- Parameters - Number of attribute values to be solved (for all frames in the frame range)
- Frames - Number of frames to solve.

Something else check/test which might have gone wrong is to make sure your 2D Markers have a non-zero weight and are enabled (unlikely but it could catch you out if your 2D points in 3DE had a weight of 0.0 - because this is copied over to Maya too).
![image](https://user-images.githubusercontent.com/891288/105097079-ec8e9800-5a9f-11eb-8bf8-61f7ce964ada.png)

I hope this helps - let me know how you go.

David

**Comment by mswed** [comment]
Hi David, 

Thank you for your quick reply! I enabled the validate button and added a few additional points. I have 22 overall and 10 points  per frame. Yet when I validate I get the following:
Valid Solves 5 | Invalid Solves 28 | Deviations 0 | Parameters 0| Frames 28

Is there a way to get more info on where exactly the solve is breaking?

Thanks, 

Moshe

**Comment by david-cattermole** [comment]
Hello Moshe,

What you describe sounds a bit strange to me.
In this text:
`Valid Solves 5 | Invalid Solves 28 | Deviations 0 | Parameters 0| Frames 28`

It tells me that the Marker deviations are not being detected, and the same as the Attribute parameters, because they are both zero.
Can you please send a screenshot of the Solver UI window with the Attributes and Markers added to the UI?
For example it should look similar to this:
![image](https://user-images.githubusercontent.com/891288/105099742-0e8a1980-5aa4-11eb-88be-b01bd58f1a14.png)


Perhaps the markers are disabled during the frame range you are solving? That's why the Solver is not detecting and deviations (because the Markers are disabled).

If it is due to the frame ranges, something else that might trip you up is that the 3DE Export 2D Tracks (and Copy 2D Tracks) tools will use the "First Frame is Frame" value to automatically set the frame offset from 3DEqualizer's frame numbers to Maya's frame numbers. I would recommend setting the "First Frame is Frame" attribute in the 3DE Attribute Editor to the start frame of your image sequence - this will allow the tools to automatically convert into the image sequence frame values, rather than 3DE's default behaviour to start at frame 1.

David

**Comment by mswed** [comment]
Hi David, 

That is indeed strange. I hoping I'm just doing something wrong :) but I can't figure out what it might be. Some of the markers are disabled during different parts of the track, but overall at least in 3de, I should have at least 10 enabled points per frame. In 3de I'm also able to get a solve using both the default solver and the lsf solver. 

Here's my UI:
![mmsolver](https://user-images.githubusercontent.com/29103764/105103532-bf7dbd80-5a7e-11eb-9e9b-49cddb1f5982.png)

And this is what I get when I hit Solve:
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1001] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1038] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1041] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1043] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1046] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1050] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1052] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1059] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1063] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1064] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1074] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1075] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1078] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1079] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1084] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1085] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1086] // 
// Warning: mmSolver._api.execute : Invalid parameters and errors, skipping solve: [1089] // 
// mmSolver.tools.solver.lib.collection : Total Time: 7.222 seconds // 
// mmSolver.tools.solver.lib.collection : Max Frame Deviation: -0.00 pixels at frame None // 
// mmSolver.tools.solver.lib.collection : Average Deviation: 0.00 pixels // 
// Warning: mmSolver.tools.solver.lib.collection : 2021-01-19 17:47:53 | Solved | Average Deviation 0.00px | Max Deviation -0.00px at None | Time 7.222sec //

**Comment by david-cattermole** [comment]
Hmm... initially, looking at the screenshot it looks ok.
The script editor output is also helpful.
Do you get any messages in the Maya Output Window (on Windows)?

Would it be possible to also get a screenshot of the Maya Outliner with the camera node, markers and `locator1`?

I'll need to investigate more...

**Comment by mswed** [comment]
Cool. Thanks so much. I will send you a screenshot and whatever I can find in the Output tomorrow.

**Comment by mswed** [comment]
So.... I found out what I was doing wrong. I never put the bundles under the object I was animating. :( I will now go hang my head in shame in the corner and mark this as closed.

**Comment by david-cattermole** [comment]
Oh great! I'm glad it's working for you.

I did think of that this morning and I was going to post this:

> One important thing is to ensure your Bundles (the green locators) are parented under the transform node you are solving (in your case `locator1`.)

Have fun and I hope mmSolver can save you some time.

David

**Comment by mswed** [comment]
It's super helpful, thank you!
