### ISSUE TITLE
Add Help and Edit Menus to All UIs

### ISSUE THREAD

**Issue by bpatchasaheb** [david-cattermole/mayaMatchMoveSolver#206]
We currently have 'Help' and 'Reset' buttons in the base window.
It would be nice to have a dedicated base window menus at least for both of them like Maya.
Help-->help, Edit-->Reset Options.
So we can make base window less clutter at the bottom.

**Comment by david-cattermole** [comment]
Hello @bpatchasaheb,

Yes, I think that is a good idea to save UI space, make things clearer/cleaner, and more similar to Maya's Option Boxes.

To add a "Help" and "Edit" menu to all tool UIs, and make them all consistent I believe we'll need a function that can be used to add each menu. This will minimise duplicated code.

The mmSolver "base window", used as the base for UI windows in mmSolver already contains a menu, so I don't think we need to add this feature to the base window exactly.

Also, since we are adding a "Help" menu, I think it would be good to add an "About mmSolver..." menu item, too.
It has also been suggested (but I haven't made an issue yet) that we add a "Send Feedback..." menu item to send bugs and suggestions, to encourage bug reports.

David

**Comment by david-cattermole** [comment]
This feature has been added as the module `mmSolver.ui.commonmenus`.

I have changed the following UIs to use the new Edit and Help menus:

- Remove Solver Nodes
- Solver UI
- Load Markers
- Project Markers on Mesh (Raycast)
- Smooth Keyframes
- User Preferences

I also fixed a bug in the help web-browser opening functions. When the "local" help source is requested, on Windows it wouldn't open in Firefox because the URL did not start with "file://". This has been changed so that local paths do start with "file://" and the problem appears to be fixed.

I will merge the current progress into `develop_v0.3.x` so that @bpatchasaheb can use it in #184 and #193.

**Comment by david-cattermole** [comment]
This feature has just been merged in #192, and should be ready for deployment.

**Comment by david-cattermole** [comment]
Something I still need to do on this is remove the "Edit > Save Settings" menu because it's never used anyway, and so it's always grayed out and is just visual noise.

**Comment by david-cattermole** [comment]
This is now implemented and ready to be released, it will be included in v0.3.13.
