### ISSUE TITLE
Project Marker on Mesh (Ray-Cast) Aim constrains bundles to camera

### ISSUE THREAD

**Issue by MichaelKarp** [david-cattermole/mayaMatchMoveSolver#230]
I am successfully using the Project Marker on Mesh (Ray-Cast) tool, animating the Bundles from the Marker, to lay on the surface of my hero polygons.

But it would be useful to have an option so that the projected Bundles would be aimed at the camera every frame (animated), which would also require the Bundle rotation channels to be revealed in the channel box.

**Comment by david-cattermole** [comment]
Hey @MichaelKarp,

I've been thinking about this issue. Unlocking the Bundle rotations (and maybe scale?) could be fine, however to err on the side of caution for v0.3.15 I will add a preference to allow this option on/off - and it will be 'off' by default.

This will allow you to test it in production and hopefully find any potential problems that might arise. If all goes well the default configuration option default will change to "on" in the next release.

**Comment by david-cattermole** [comment]
The second part to this is the ray-casting, which is "part 2", and should be fairly straight-forward.

**Comment by MichaelKarp** [comment]
FYI, mmSolver v0.3.14 has been a gigantic help on my current show. My bosses are talking glowingly about how a very difficult problem was easily solved with mmSolver. Now I am training other artists on the easy to understand procedure.

We look forward to the minor fixes in mmSolver v0.3.15

**Comment by david-cattermole** [comment]
That's good to hear @MichaelKarp!

I've implemented this change now.

While implementing the change, I don't think there's any need for a configuration option.
Instead all bundles will display the translate, rotate and scale attributes by default, however translate values will be unlocked, and rotation and scale will be locked, same as before. Therefore the display is the only difference, and no tools should break as a result of this.

To see the rotation attributes, only newly created bundles will have them visible. 
Although annoying it is possible to make the rotation attributes "keyable" manually via the Channel Box edit menu.

Regardless of if the attributes are visible, the tool will automatically unlock/relock the attributes with the "unlock/relock" checkbox.

The change to the Marker Raycast tool now contains a "Bundle Rotation" option, with 3 different values;
- No Change
- Aim at Camera
- Mesh Normal

The "forward" axis is +Z - the Maya Move manipulator blue arrow will aim towards the camera, or away from the hit mesh.

I added the Mesh Normal option because although it wasn't requested, it was trivial to add, and I thought it might be cool.

Additionally, for coding folks, I've added the `mmSolver.utils.raytrace.closest_intersection_with_normal()` function, which will get the mesh normal for the hit and return it.

This will be released in v0.3.15. 

I'll close this issue for now.
