### ISSUE TITLE
Are there any plans for having a pre-compile of 0.4.1 for maya2018 on linux?

### ISSUE THREAD

**Issue by abenaventefortes** [david-cattermole/mayaMatchMoveSolver#245]
Hello! This is Alonso Benavente Fortes, Pipeline Technical Director for the Integration (Matchmove department) at Digital Domain.

We are in the process of implementing mmsolver for our integration department, and we where wondering if there any plans of releasing a precompile of version 0.4.1 for maya2018 on linux?

Please contact me at abenavente@d2.com if you have any question or if you would like to chat!

**Comment by david-cattermole** [comment]
Hello Alonso,

I'm sorry but I was unable to find a way to create a Docker configuration with all the software requirements to build mmSolver for Maya 2018. Maya 2019 was the earliest set of requirements that I could get to work. On the other hand, Windows builds worked with a newer compiler, that's why they are provided.

The current Docker files are here (for Maya 2019 to 2023):
https://github.com/david-cattermole/mayaMatchMoveSolver/tree/master/share/docker

Relevant Maya API documentation: 
https://help.autodesk.com/view/MAYAUL/2018/ENU/?guid=__files_Setting_up_your_build_environment_Linux_environments_32bit_and_64bit_htm
https://help.autodesk.com/view/MAYAUL/2018/ENU/?guid=__files_Setting_up_your_build_environment_Linux_compiler_requirement_htm

I believe the main issue is that "devtoolset-2" is no longer supported or downloadable from any Redhat/CentOS packages repos and as a result I cannot use it. 
You can see this thread on the VFX Platform mailing list:
https://groups.google.com/g/vfx-platform-discuss/c/_-_CPw1fD3c

I am currently using https://github.com/wwfxuk/centos-vault-scl as a stop-gap to support the (Redhat unsupported) devtoolset versions that I'm currently using in the Docker containers.

If you are able to create a Docker file that supports Maya 2018 with publicly downloadable repos/hacks, I'd be very grateful.
If you are able to create a private Docker file with the compiler requirements, you can follow the build instructions here:
https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/BUILD_LINUX.md

David

**Comment by david-cattermole** [comment]
I haven't got any plans to support Maya 2018 at the moment, but contributions are welcome.

I'm closing this issue for now, as it's stale.
